<?php

namespace Database\Seeders;

use App\Models\Ministry;
use Illuminate\Database\Seeder;

class MinistrySeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $ministries = [
            // INTER-GENERATIONAL MINISTRIES
            [
                'name' => 'Choir Ministry',
                'slug' => 'choir-ministry',
                'category' => 'inter-generational',
                'ministry_category' => 'Worship',
                'age_range' => null,
                'description' => 'Our choir brings together voices from all generations to lead worship and glorify God through music.',
                'content' => 'We practice weekly and perform during Sunday services and special occasions.',
                'image' => 'https://images.unsplash.com/photo-1507838153414-b4b713384a76?w=800&h=600&fit=crop',
                'leader' => 'Choir Director',
                'leader_phone' => '+233 24 123 4567',
                'contact_email' => 'choir@pcgmonninger.org',
                'meeting_schedule' => 'Saturdays, 4:00 PM',
                'location' => 'Church Auditorium',
                'featured' => true,
                'active' => true,
            ],
            [
                'name' => 'Evangelism Team',
                'slug' => 'evangelism-team',
                'category' => 'inter-generational',
                'ministry_category' => 'Outreach',
                'age_range' => null,
                'description' => 'Our evangelism team reaches out to the community with the Gospel message.',
                'content' => 'Members of all ages participate in outreach programs, community events and personal evangelism.',
                'image' => 'https://images.unsplash.com/photo-1469571486292-0ba58a3f068b?w=800&h=600&fit=crop',
                'leader' => 'Evangelism Coordinator',
                'leader_phone' => '+233 24 234 5678',
                'contact_email' => 'evangelism@pcgmonninger.org',
                'meeting_schedule' => 'First Saturday, 3:00 PM',
                'location' => 'Church Hall',
                'featured' => true,
                'active' => true,
            ],
            [
                'name' => 'Prayer Ministry',
                'slug' => 'prayer-ministry',
                'category' => 'inter-generational',
                'ministry_category' => 'Prayer & Intercession',
                'age_range' => null,
                'description' => 'The prayer ministry intercedes for the needs of our congregation and community.',
                'content' => 'We believe in the power of prayer and gather regularly to seek God\'s face together.',
                'image' => 'https://images.unsplash.com/photo-1528459801416-a9e53bbf4e17?w=800&h=600&fit=crop',
                'leader' => 'Prayer Coordinator',
                'leader_phone' => '+233 24 345 6789',
                'contact_email' => 'prayer@pcgmonninger.org',
                'meeting_schedule' => 'Wednesdays, 6:00 PM',
                'location' => 'Prayer Room',
                'featured' => false,
                'active' => true,
            ],
            [
                'name' => 'Ushering Ministry',
                'slug' => 'ushering-ministry',
                'category' => 'inter-generational',
                'ministry_category' => 'Service',
                'age_range' => null,
                'description' => 'Our ushers serve with excellence, ensuring everyone feels welcomed and comfortable during worship.',
                'content' => 'The ushering team assists with seating, offering collection and maintaining order during services.',
                'image' => 'https://images.unsplash.com/photo-1511632765486-a01980e01a18?w=800&h=600&fit=crop',
                'leader' => 'Head Usher',
                'leader_phone' => '+233 24 456 7890',
                'contact_email' => 'ushers@pcgmonninger.org',
                'meeting_schedule' => 'Monthly training',
                'location' => 'Church Auditorium',
                'featured' => false,
                'active' => true,
            ],
            
            // GENERATIONAL MINISTRIES
            [
                'name' => 'Children\'s Service (CS)',
                'slug' => 'childrens-service',
                'category' => 'generational',
                'ministry_category' => 'Children & Family',
                'age_range' => '0-12 years',
                'description' => 'Nurturing young hearts in the love of Jesus through Sunday School, Bible stories, worship and fun activities.',
                'content' => 'Teaching foundational faith principles to children through age-appropriate Bible teaching, fun activities and spiritual guidance.',
                'image' => 'ministries/placeholder-children.jpg',
                'leader' => 'Children\'s Ministry Director',
                'leader_phone' => '+233 24 567 8901',
                'contact_email' => 'children@pcgmonninger.org',
                'meeting_schedule' => 'Sundays, 9:00 AM',
                'location' => 'Children\'s Hall',
                'featured' => true,
                'active' => true,
            ],
            [
                'name' => 'Junior Youth (JY)',
                'slug' => 'junior-youth',
                'category' => 'generational',
                'ministry_category' => 'Youth & Young Adults',
                'age_range' => '13-19 years',
                'description' => 'Empowering teenagers to grow in faith and become leaders for Christ.',
                'content' => 'Dynamic worship, relevant teaching and meaningful relationships for teenagers navigating faith and life.',
                'image' => 'https://images.unsplash.com/photo-1529156069898-49953e39b3ac?w=800&h=600&fit=crop',
                'leader' => 'Youth Pastor',
                'leader_phone' => '+233 24 678 9012',
                'contact_email' => 'youth@pcgmonninger.org',
                'meeting_schedule' => 'Saturdays, 3:00 PM',
                'location' => 'Youth Center',
                'featured' => true,
                'active' => true,
            ],
            [
                'name' => 'Young People\'s Guild (YPG)',
                'slug' => 'young-peoples-guild',
                'category' => 'generational',
                'ministry_category' => 'Youth & Young Adults',
                'age_range' => '18-25 years',
                'description' => 'Equipping young people to live purposefully for Christ in their formative years.',
                'content' => 'Biblical wisdom and peer support for young people in their journey of faith and personal growth.',
                'image' => 'https://images.unsplash.com/photo-1511632765486-a01980e01a18?w=800&h=600&fit=crop',
                'leader' => 'YPG Coordinator',
                'leader_phone' => '+233 24 789 0123',
                'contact_email' => 'ypg@pcgmonninger.org',
                'meeting_schedule' => 'Fridays, 6:00 PM',
                'location' => 'Fellowship Hall',
                'featured' => true,
                'active' => true,
            ],
            [
                'name' => 'Young Adult Fellowship (YAF)',
                'slug' => 'young-adult-fellowship',
                'category' => 'generational',
                'ministry_category' => 'Youth & Young Adults',
                'age_range' => '26-35 years',
                'description' => 'Building strong foundations for young adults navigating life, career, relationships and faith.',
                'content' => 'Biblical wisdom and peer support for young adults in their journey of faith and personal growth.',
                'image' => 'https://images.unsplash.com/photo-1529156069898-49953e39b3ac?w=800&h=600&fit=crop',
                'leader' => 'YAF Coordinator',
                'leader_phone' => '+233 24 789 0124',
                'contact_email' => 'yaf@pcgmonninger.org',
                'meeting_schedule' => 'Saturdays, 5:00 PM',
                'location' => 'Fellowship Hall',
                'featured' => true,
                'active' => true,
            ],
            [
                'name' => 'Women\'s Fellowship',
                'slug' => 'womens-fellowship',
                'category' => 'generational',
                'ministry_category' => 'Fellowship',
                'age_range' => 'All adult women',
                'description' => 'Strengthening women in faith, fellowship and service to God and community.',
                'content' => 'Bible study, prayer and mutual encouragement for women of all ages.',
                'image' => 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=800&h=600&fit=crop',
                'leader' => 'Women\'s Ministry Leader',
                'leader_phone' => '+233 24 890 1234',
                'contact_email' => 'women@pcgmonninger.org',
                'meeting_schedule' => 'Wednesdays, 5:00 PM',
                'location' => 'Women\'s Hall',
                'featured' => false,
                'active' => true,
            ],
            [
                'name' => 'Men\'s Fellowship',
                'slug' => 'mens-fellowship',
                'category' => 'generational',
                'ministry_category' => 'Fellowship',
                'age_range' => 'All adult men',
                'description' => 'Building godly men of character who lead with integrity and serve with passion.',
                'content' => 'Mentorship, Bible study and fellowship activities for men committed to following Christ.',
                'image' => 'https://images.unsplash.com/photo-1511632765486-a01980e01a18?w=800&h=600&fit=crop',
                'leader' => 'Men\'s Ministry Leader',
                'leader_phone' => '+233 24 901 2345',
                'contact_email' => 'men@pcgmonninger.org',
                'meeting_schedule' => 'Saturdays, 7:00 AM',
                'location' => 'Men\'s Hall',
                'featured' => false,
                'active' => true,
            ],
            [
                'name' => 'Senior Citizens Ministry',
                'slug' => 'senior-citizens-ministry',
                'category' => 'generational',
                'ministry_category' => 'Care & Support',
                'age_range' => '60+ years',
                'description' => 'Honoring and caring for our senior members with love, respect and spiritual support.',
                'content' => 'Fellowship, spiritual support and practical assistance for our elderly members through regular gatherings and visitation programs.',
                'image' => 'https://images.unsplash.com/photo-1581579438747-1dc8d17bbce4?w=800&h=600&fit=crop',
                'leader' => 'Senior Ministry Coordinator',
                'leader_phone' => '+233 24 012 3456',
                'contact_email' => 'seniors@pcgmonninger.org',
                'meeting_schedule' => 'Monthly gatherings',
                'location' => 'Senior Center',
                'featured' => false,
                'active' => true,
            ],
        ];

        foreach ($ministries as $ministryData) {
            // Update or create ministry
            Ministry::updateOrCreate(
                ['slug' => $ministryData['slug']],
                $ministryData
            );
            $this->command->info('✓ Updated/Created ministry: ' . $ministryData['name']);
        }

        $this->command->info('Ministries seeding completed!');
    }
}
